### ISSUE TITLE
UML diagram needs update

### ISSUE THREAD

**Issue by ziogaschr** [yankodimitrov/SwiftPasscodeLock#10]
There is no reference to `PasscodeLockPresenter`. It might be nice to include it in the UML.

Have you found an automated way for creating the UMLs in Xcode?

**Comment by yankodimitrov** [comment]
I've removed the UML class diagram in the new version. However if there are any requests I may put it back. 

On your question: nope Im using `Umlet` to create UML diagrams.

Thanks!
