### ISSUE TITLE
Make `PasscodeViewController` a Singleton instance

### ISSUE THREAD

**Issue by ziogaschr** [yankodimitrov/SwiftPasscodeLock#12]
It might be helpful to make `PasscodeViewController` a singleton so as we can easily ask for the Lock screen in a single line when needed.
Also it will be easier to support methods like `isLockscreenDisplayed`.

All this are easy to be handled in an app, but I was wondering if you like them in the lib, so as it will be easier for smaller projects to handle things.

**Comment by yankodimitrov** [comment]
I don't think that the `PasscodeLockViewController` need to be a Singleton.
