### ISSUE TITLE
Bug:  TouchID not showing when Passcode enabled

### ISSUE THREAD

**Issue by gblotter** [yankodimitrov/SwiftPasscodeLock#15]
If I toggle the passcode switch to 'on', set a passcode, and then leave the app.  Upon returning, I'm greeted with the new passcode, but no touchID authentication modal.  I have to kill the app, and then enter it to get the touchID authentication modal to present.

**Comment by ziogaschr** [comment]
I think this is because the `passcodeLockPresenter` is lazy initiated without touchID support on first app launch. I was able to handle that by making the [`passcodeViewController` public](https://github.com/ziogaschr/SwiftPasscodeLock/commit/13139fd4d07aaa3468425678986054465177218a#diff-433fe2ae5d6fa0c59ba2f94fed23d607R14) and then changing its properties from the app while Passcode is set.

I can add an example on this @gblotter if you want. But I was thinking that @yankodimitrov will handle this in the `swift-2.0` branch differently.

**Comment by yankodimitrov** [comment]
Could someone test for that on the new version?

Thanks!

**Comment by gblotter** [comment]
On it...

**Comment by yankodimitrov** [comment]
It seems that this is the intended behaviour by the system:

**LAErrorSystemCancel**

>Authentication was canceled by system—for example, if another application came to foreground while the authentication dialog was up.

**Comment by gblotter** [comment]
Right... I believe that just means that it needs to be implemented differently, i.e. when the applicationDidEnterBackground() method is called, it's throwing up the passcode lock screen.  Somehow the applicationWillEnterForeground() method need to be used?  

I know that other apps do it just fine... BUT... Those are just my thoughts.  If this is "good enough" for now, that's cool.  You're the author, designer, and decision maker :)

**Comment by yankodimitrov** [comment]
I have never said that it is good enough. As currently I cannot test on a device with TouchID it is somehow hard for me to fix the issue and I will leave it open for now. Also any PR are welcome.

**Comment by ziogaschr** [comment]
@yankodimitrov this is why I have moved some of the logic in the old project in applicationWillEnterForeground. When I will install Swift 2.0, I will try to suggest a PR.

**Comment by yankodimitrov** [comment]
Could someone test my latest commit (not the latest release) with the TouchID request fix on a device with TouchID?

If everything is working properly I will publish a new release.

Thanks!

**Comment by yankodimitrov** [comment]
The new simulator found in Xcode 7 GM can simulate TouchID authentication. Just tested and fixed the issue.

Check out the release version 1.0.1

Thanks!
