### ISSUE TITLE
Console warning: "Unbalanced calls to begin/end appearance transitions" on App start

### ISSUE THREAD

**Issue by gblotter** [yankodimitrov/SwiftPasscodeLock#18]
When a passcode is set, and you start the app, the following warning appears in the console:

2015-09-03 08:31:41.141 PasscodeLockDemo[2751:663098] Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x12f6517b0>.

After doing some research, this issue is caused from line 21 on the PasscodeLockPresenter.swift file.  When creating a UIViewController() w/o specifying the nib file to pass in to the initializer, it is causing an animation when it's added to the window, but there are other animations already currently taking place via the normal startup means on the mainWindow object (best I can tell.)

**Comment by gblotter** [comment]
I guess I should've mentioned this, that the pull request that I created has a fix for this.

**Comment by yankodimitrov** [comment]
Thanks!

**Comment by yankodimitrov** [comment]
Actually the warning is caused by presenting the PasscodeLockViewController before the rootViewController of the passcode window has a chance to appear. Your pull request has some issues that I will fix in my next commit. 

Thanks!
