### ISSUE TITLE
AlertController wrong position change after unlock

### ISSUE THREAD

**Issue by zoli7** [yankodimitrov/SwiftPasscodeLock#2]
When I leave an alertcontroller open and close the app or leave the phone in standby, when I return to the app and unlock it, the alertcontroller is misplaced in top of the screen.
This happens for all the alertcontrollers.

**Comment by zoli7** [comment]
For now I modified findTopMostControllerInWindow that partially fixes the problem by dismissing the alertcontroller:

    private func findTopMostControllerInWindow(window: UIWindow?) -> UIViewController? {
        
        var topController: UIViewController?
        
        if let mainWindow = window {
            
            topController = mainWindow.rootViewController
        
            while topController?.presentedViewController != nil {
                if let alertController = topController?.presentedViewController as? UIAlertController {
                    topController?.dismissViewControllerAnimated(false, completion: nil)
                    break
                } else {
                    topController = topController?.presentedViewController
                }
            }
        }
        
        return topController
    }

But the best way would be to preserve the state of alertcontroller and not to dismiss it.
I will get back if I find a good solution.

**Comment by yankodimitrov** [comment]
Hi,

In the new version I've implemented the passcode lock presenter to use a separate `UIWindow` and now the presented `UIAlertController` stays in the correct place after you enter your passcode.

Also works with `UIActivityViewController`.

Thanks!
