### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by karlml** [yankodimitrov/SwiftPasscodeLock#28]
It would be great to see this implemented with keychain

**Comment by waltermvp** [comment]
@yankodimitrov I have a implementation already done. Should I send a PR?

**Comment by twofish187** [comment]
Can you please implement the splash view in this new version?

**Comment by waltermvp** [comment]
What secure splash screen?

**Comment by twofish187** [comment]
When the taskmanager in iOS is called and the content of the app is blurred out. In a previous version this was implemented by adding a "splashview". So was it called in code.

**Comment by waltermvp** [comment]
@twofish187  please create a new issue this is a unrelated toic

**Comment by yankodimitrov** [comment]
To make the library versatile there should be no default implementation of the <code> PasscodeRepositoryType</code> protocol. It should be left as an implementation detail for the given application.
