### ISSUE TITLE
LAContext() support for iOS 7

### ISSUE THREAD

**Issue by jeslinjohnson** [yankodimitrov/SwiftPasscodeLock#3]
I have been working in a project and I used this library for passcode lock. It is running smoothly in iOS 8. But when I try to change the device to IOS 7, app is crashed in this line :
 let context = LAContext - (PasscodeViewController) due to no support for iOS 7. So what is the strategy that I could use instead?

**Comment by yankodimitrov** [comment]
If you are using Swift 2.0 use the new availability checking:

```swift
if #available(iOS 8, *) { 
    ...
} else {
    ...
}
```

Thanks!
