### ISSUE TITLE
add a background image to passcodelockview.xib

### ISSUE THREAD

**Issue by moh1122** [yankodimitrov/SwiftPasscodeLock#30]
Hello
great app its amazing
but I'mfacing a prob when i want to add a background image to PasscodeLockView.xib it wont appear when i run the project and it says in the debugger description could not load "background image referenced from a nib in the bundle with identifier .....
any clue how to show the background image.
thank you
/MM

**Comment by moh1122** [comment]
In the Project View, click project name
Select your target and select "Build Phases" tab
Drag your image file into your "Copy Bundle Resources" section
That fixed it for me.

thnk u man

**Comment by yankodimitrov** [comment]
Awesome :+1: 

Thanks
