### ISSUE TITLE
Problem with PasscodeView.xib

### ISSUE THREAD

**Issue by thomascsorbamedia** [yankodimitrov/SwiftPasscodeLock#4]
Hi, i tried importing your project into mine.
When i open PasscodeView.xib it gives my 70 warnings.

    PasscodeView.xib: warning: IB Designables: Ignoring user defined runtime attribute for key path "activeColor" on instance of "UIView". Hit an exception when attempting to set its value: [<UIView 0x7fd81acd87d0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key activeColor.

I tried finding a solution on google, but i couldn't find one, maybe you know the answer?
Please reply soon, thanks in advance.

Thomas

**Comment by yankodimitrov** [comment]
Fixed in the new version.

Thanks!
