### ISSUE TITLE
Error while running carthage update

### ISSUE THREAD

**Issue by LucasKovacs** [yankodimitrov/SwiftPasscodeLock#42]
I have opened the app and I got the following error:

Module file was created by an older version of the compiler; rebuild 'PasscodeLock' and try again: /Users/UserName/Documents/xcode/AppName/AppName/PasscodeLock.framework/Modules/PasscodeLock.swiftmodule/i386.swiftmodule

So I try to rebuild doing this:
carthage update

But I got the following errors:

/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/Views/PasscodeSignButton.swift:74:33: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/Views/PasscodeSignButton.swift:75:33: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/PasscodeLockViewController.swift:110:57: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/PasscodeLockViewController.swift:111:57: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/Views/PasscodeSignButton.swift:74:33: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/Views/PasscodeSignButton.swift:75:33: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/PasscodeLockViewController.swift:110:57: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/PasscodeLockViewController.swift:111:57: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/Views/PasscodeSignButton.swift:74:33: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/Views/PasscodeSignButton.swift:75:33: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/PasscodeLockViewController.swift:110:57: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/PasscodeLockViewController.swift:111:57: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/Views/PasscodeSignButton.swift:74:33: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/Views/PasscodeSignButton.swift:75:33: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/PasscodeLockViewController.swift:110:57: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/UserName/Documents/xcode/AppName/Carthage/Checkouts/SwiftPasscodeLock/PasscodeLock/PasscodeLockViewController.swift:111:57: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead

**Comment by yanniks** [comment]
Warnings are no problem. For now, they're just to tell you that you should consider updating your code in the near future.
