### ISSUE TITLE
Cancel in all passcode states.

### ISSUE THREAD

**Issue by raugustinas** [yankodimitrov/SwiftPasscodeLock#54]
By default .SetPasscode state has the cancel button. But in .EnterPasscode state cancel button is missing. Is there a simple way to enable cancel button in .EnterPasscode state?

Awesome lib! 
Thanks!
@ziogaschr , @szappanyos , @yankodimitrov , @maximbilan , @gblotter

**Comment by raugustinas** [comment]
I've created custom PasscodeLockStateType with allowed cancelation.

**Comment by kiokumicu** [comment]
Can you give an example?

**Comment by raugustinas** [comment]
Just set isCancelableAction to true in EnterPasscodeState init.

**Comment by kiokumicu** [comment]
You copy EnterPasscodeState.swift in your own directory?

**Comment by raugustinas** [comment]
Yes, I've forked the whole project and edited it.

**Comment by kiokumicu** [comment]
ok, thx
