### ISSUE TITLE
Support of passcodes longer than 4 digits

### ISSUE THREAD

**Issue by PanosSakkos** [yankodimitrov/SwiftPasscodeLock#55]
Great repository, thanks for sharing! :clap: 

Do you have any plans for supporting passcodes longer than 4 digits? i.e. would be great.

If not, do you want to give me some pointers on how to do it?

Thanks!
:panos

**Comment by ziogaschr** [comment]
Try to set `PasscodeLockConfigurationType.passcodeLength = 6`

Then you will have to copy both the `.xib` file and its `ViewController.swift` file and update it in order it can handle 6 placeholders.

I have made it for our App, but not in a generic way so as UI get's updated accordingly from `passcodeLength`.
When I find some time I might look into making a generic PR.

**Comment by PanosSakkos** [comment]
Great!

I will wait for your fix, since I prefer to use the component as a pod, instead of forking it :smile: 

Thanks!
:panos

**Comment by ziogaschr** [comment]
There is no need to fork it.

You just have to create a subclass in your project and follow the [docs](https://github.com/yankodimitrov/SwiftPasscodeLock#custom-design) about the `xib` file.

I am not planning to work on this early on, so if you need this soon enough then please give the above a try and I will be happy to give you any advices needed here.

Cheers,
Chris

**Comment by PanosSakkos** [comment]
Then that's great, I will give it a try myself.

Thanks for the pointers!

Thanks!
:panos

**Comment by le4ker** [comment]
@ziogaschr I managed to get the 6 character pin to work, but the two new placeholders are not behaving like the existing 4, they always stay at the same state. Their Class and Module is set to the same classes at the first 4 placeholders.

By the way I didn't subclass any PasscodeLock class (I just edited the PasscodeLockView.xib and then set the passcodeLength of my configuration to 6), so probably this is my missing piece for completing it. Any pointers would be very appreciated! 😄 

Thanks!
:panos

**Comment by le4ker** [comment]
I had to set the their referencing outlets to the file's owner 😄 

Thanks for the guidelines! 👍

**Comment by ziogaschr** [comment]
Great news. I am super happy that it worked :)

**Comment by le4ker** [comment]
@ziogaschr by the way, how can I fix the non persisted failed passcode attempts? I read the source code but with my (very limited) swift knowledge I can't find a non-hackish way to fix that :disappointed:
