### ISSUE TITLE
Simultaneous accesses to *, but modification requires exclusive access

### ISSUE THREAD

**Issue by riccardoch** [yankodimitrov/SwiftPasscodeLock#87]
I've an app written in Swift 4, but it crashes at the end of Passcode set.
Here the lines of code I used to open Passcode set interface:
```swift
let passcodeVC = PasscodeLockViewController(state: .setPasscode, configuration: configuration)
present(passcodeVC, animated: true, completion: nil)
passcodeVC.successCallback = { lock in
    passcodeVC.dismiss(animated: true, completion: nil)
}
```

Here what the console has printed:
```
Simultaneous accesses to 0x1c40ed9c8, but modification requires exclusive access.
Previous access (a modification) started at Smartface`PasscodeLock.addSign(_:) + 912 (0x104a269bc).
```

That is the highlighted function when the app crashes (it's in _PasscodeLock.swift_):
```swift
open func changeStateTo(_ state: PasscodeLockStateType) {
    self.lockState = state // this assignment is highlighted when the app crashes
    delegate?.passcodeLockDidChangeState(self)
}
```

**Comment by DominikBucher12** [comment]
You can fix it on your own since this is thread-related problem, this should do:

 DispatchQueue.main.async {
            self.lockState = state
            self.delegate?.passcodeLockDidChangeState(self)
        }

**Comment by DominikBucher12** [comment]
And btw this repo is dead, I would move it to mine where I fixed the UI and so...

**Comment by riccardoch** [comment]
@DominikBucher12 thanks! it solves the problem!
I'll refer to you repo for future updates ;)

**Comment by ziogaschr** [comment]
Hello guys, I am not sure if it is dead, but it indeed it looks like it is.

Me and @velikanov trying to keep this nice package alive [here](https://github.com/velikanov/SwiftPasscodeLock). If you would like, please contribute there in order we keep all in sync for all of us.

If you are willing to contribute even more, let's discuss with @velikanov in order he makes you a contributor too.

**Comment by DominikBucher12** [comment]
@ziogaschr  totally right, I think there are too much forks of this, it should be kept consistent all across... Does your solution provide stackViews and more sophisticated autolayout?

**Comment by ziogaschr** [comment]
We have added a lot of changes/features there and I think I have even merged the extra stuff in the 10 different commits. Some fixes in autolayout have been done, but not much and nothing for stackViews I think. Please check and if you think that it worths continuing there, make a PR with your suggestions. 👍

**Comment by DominikBucher12** [comment]
ok, abandoning my project and moving to contributing to this one..

**Comment by ziogaschr** [comment]
Make a PR first. I will try to review it, but can't promise that I will do this asap.
