### ISSUE TITLE
Not maintained?

### ISSUE THREAD

**Issue by jooneyp** [yankodimitrov/SwiftPasscodeLock#91]
I am using this very useful and I've just ended up for supporting Swift4 and FaceID compatible.
I want to send Pull requests but it doesn't seemed to be updated for 2 years.
This project has many stars, users and also has many issues to solve.
If you want, can you transfer me for ownership of this project?
Thanks for your great contribute.

**Comment by ziogaschr** [comment]
Hello @jooneyp, I am not sure if this main repo is maintained, although I and @velikanov https://github.com/velikanov/SwiftPasscodeLock try to maintain and we also have added some stuff here. Feel free to make PR's and we might also give you access as a maintainer too.

I am currently reviewing https://github.com/velikanov/SwiftPasscodeLock/pull/53, but would like to check your implementation for FaceID, as the other is not backward compatible.

Update: you can check the new FaceID PR at https://github.com/velikanov/SwiftPasscodeLock/pull/54

**Comment by jooneyp** [comment]
Thanks for your contribute!
I'll keep watching this project.
Closing this issue! 😄
